# Generated by Django 3.1.7 on 2021-03-24 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(verbose_name='write here')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='publish')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('approved_comments', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='publish', verbose_name='slug')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
